package com.customer.ordermanagementsystem.domain.item;


public enum Type {
    PIZZA_NORMAL, PIZZA_BIG, PIZZA_SPECIAL,
    POLIEVKA, SALAT, OMACKA, POCHUTINA,
    ZEMIAK_SPECIAL, BAGETA, CESTOVINA,
    GURMANSKE, OBALOVANE, FIT, RIZOTO, SLADKOST, MASOVE_JEDLO,
    WRAP_FRITTATA, NIECO_MALE_POD_ZUB,
    PRILOHA, NAPOJ, DOPLNOK,
    PIVO, VINO, ALKOHOL;
}